### ISSUE TITLE
No mention of HASURA_GRAPHQL_JWT_SECRET

### ISSUE THREAD

**Issue by Ciboulette** [rvamsikrishna/hasura-firebase-flutter-boilerplate#1]
Hey, 

Is-it normal that you don't mention the setup of the env variable `HASURA_GRAPHQL_JWT_SECRET`, to generate valid JWT?

**Comment by rvamsikrishna** [comment]
Oops, I forgot to mention that step in the readme. It is required. I updated the Readme. Thanks for mentioning.😀
